#    ________________________
#   |         汉化by:        |
#   |       酷车手BB弹       |
#   | ====================== |
#   |     感谢雪妮的指导~    |
#   |   感谢MC小白桑的提出~  |
#   |________________________|
#
#Tax amount (decimal) - Eg, P1 buys $50 worth of stuff from P2.  Therefore, P1 loses $50, P2 gains $(1-0.05)*50, and tax-account gains $(0.05)*50.
#税额 - 比如P1在P2的商店买了价值50块的东西，P1将扣除50块，P2将得到(1-0.05)*50块，而税收账户将得到(0.05)*50块
tax: 0.05

#The fake player who money from taxing people goes to
#税收人ID（强烈建议改成腐竹的ID）
tax-account: tax

#Whether or not to show taxes paid when selling to a shop
#当出售物品时是否显示扣除的税额
show-tax: false

#Should we log transactions/creations to Bukkit\Plugins\QuickShop\qs.log?
#是否对商店操作进行记录
log-actions: true

#For item-item based economies that don't use virtual coins.
#设置为true时将使用金属铸币经济而不使用虚拟货币
whole-number-prices-only: false

#Force bukkit chat handler (https://github.com/KaiKikuchi/QuickShop/issues/10)
#设置为true则启用HeroChat（需要HeroChat作为前置）
force-bukkit-chat-handler: false

database:
    mysql: false
    host: localhost
    port: 3306
    database: quickshop
    user: root
    password: passwd
    
#Limits the number of shops a person can create and own at a single time.
#设置玩家的商店数量最大只能拥有多少个
limits:
    #Disable these if you're not using them! If this is false, the rest of this section is ignored
    #设置为false将会关闭这项功能
    use: false
    
    #The default number of shops players can make
    #默认玩家拥有商店的最大数量
    default: 10
    
    #Players with these permissions can create these amounts of shops.
    #可设置该权限的玩家能拥有商店的最大数量
    ranks:
        #Anyone with 'quickshop.vip' permissions, can create 20 shops instead of 10.
        #拥有'quickshop.vip'权限的玩家可创建20个，而不是10个
        quickshop.vip: 20 #VIP最大可制作20个商店

#A list of block (materials) which can be used to create shops.
#可用来创建为商店的方块列表
#By default, chests are added to this list.
#默认拥有箱子
#This will only work for blocks which implement InventoryHolder
#这些可用于商店的方块只能是可实现持有人库存
#in other words, no enderchest shops, no shops on dirt blocks, etc.
#也就是说，无法使用末影箱、泥土等等作为商店的方块
#May cause unexpected behaviour with some blocks... Eg don't make a 
#shop on a hopper (It sucks the display item in) and furnace shops
#allow players to put whatever item they want in all 3 slots and
#dispenser shops aren't protected from redstone... Etc.
shop-blocks:
    - CHEST
    - TRAPPED_CHEST

shop:
    #Cost to make a stall
    #制作一个商店需要花的钱
    cost: 10
    #Should we refund when their shops are deleted/removed/broken?
    #当商店拆除时是否退款？
    refund: false

    #Is there a fee for changing prices on a shop (Help deter endless undercutting)
    #是否启用当更改商店的价格时花费固定的费用
    price-change-requires-fee: true
    #If price changes require a fee, how much is the fee
    #一次多少钱
    fee-for-price-change: 50

    #Should we try and lock their shops from other players, so people can't steal from them?
    #是否对商店进行上锁（如果为true无法和别人一起管理商店，如果为false可用牌子锁或LWC锁住并共享给别人）
    lock: true
    
    #Should we require players be sneaking to create and use shops?
    #是否需要潜行才能进行创建或交易？
    sneak-to-create: false
    sneak-to-trade: false
    
    #Should we automatically create the sign for the chest?
    #自动在箱子中间创建牌子（设置为false时可自己自定义牌子）
    auto-sign: true
    
    #If a player owns an unlimited shop, should they receive the cash from it or not?
    #如果拥有无限商店，是否可收取费用
    #If you buy from YOUR unlimited shop, you will NEVER be charged $$, regardless of this setting
    pay-unlimited-shop-owners: false
    
    #Should we place display items on the chests? This may cause duped items, especially for modded servers.
    #是否显示悬浮物？【警告：可用漏洞刷物品，可使用其他插件修复此问题后开启】
    display-items: false
    
    #Should we place item frames on chests?
    #是否放置物品展示框在箱子？
    frame-items: false
    
    #When someone uses /qs find <item>, how far should we search in blocks?
    #当使用/qs find <item>时，可以搜索到距离多远的方块？【太高服务器崩了别怪我】
    #This command lets users shop quickly without wasting time searching
    #这个命令可让玩家更快的找到需要的东西
    #Settings > 100 WILL cause lag. Don't do it, or don't cry when your server lags.
    #当设置超过100时服务器将会产生延迟
    find-distance: 45

#List of items to disallow selling of.  Anyone with quickshop.bypass.<itemID> can bypass it    
#禁止交易的物品，可给予quickshop.bypass.<itemID>权限无视黑名单
blacklist:
- 7 #Bedrock
    
    
#List of items with restricted prices. Format: <ItemID>;<MinPrice>;<MaxPrice>
#用于限制物品价格，格式:<物品ID>;<最低售价>;<最高售价>
price-restriction:
- Bedrock;100;200

#Custom name for items. Format: <ItemID[*DataValue]>;<CustomSignName>;<CustomFullName>
#自定义物品的名字
custom-items-name:
#- NETHER_STALK;Nether Wart;Nether Wart
- 0;空气;空气
- 1;石头;石头
- 2;草方块;草方块
- 3;泥土;泥土
- 4;圆石;圆石
- 5;木板;木板
- 6;树苗;树苗
- 7;基岩;基岩
- 8;水;水
- 9;静态水;静态水
- 10;熔岩;熔岩
- 11;静态熔岩;静态熔岩
- 12;沙子;沙子
- 13;沙砾;沙砾
- 14;金矿石;金矿石
- 15;铁矿石;铁矿石 
- 16;煤矿石;煤矿石
- 17;木头;木头
- 18;树叶;树叶
- 19;海绵;海绵
- 20;玻璃;玻璃
- 21;青金石矿石;青金石矿石
- 22;青金石块;青金石块
- 23;发射器;发射器
- 24;沙石;沙石
- 25;音符盒;音符盒
- 26;床;床
- 27;充能铁轨;充能铁轨
- 28;探测铁轨;探测铁轨
- 29;粘性活塞;粘性活塞
- 30;蜘蛛网;蜘蛛网
- 31;草丛 ;草丛 
- 32;枯死的灌木;枯死的灌木
- 33;活塞;活塞
- 34;活塞臂;活塞臂
- 35;羊毛;羊毛
- 24;移动的活塞臂;移动的活塞臂
- 37;蒲公英;蒲公英
- 38;罂粟;罂粟
- 39;棕色蘑菇;棕色蘑菇
- 40;红色蘑菇;红色蘑菇
- 41;金块;金块
- 42;铁块;铁块
- 43;双石台阶;双石台阶
- 44;石台阶;石台阶
- 45;砖块;砖块
- 46;TNT;TNT
- 47;书架;书架 
- 48;苔石;苔石
- 49;黑曜石;黑曜石
- 50;火把;火把
- 51;火;火
- 52;刷怪箱;刷怪箱
- 53;橡木楼梯;橡木楼梯
- 54;箱子;箱子
- 55;红石线;红石线
- 56;钻石矿石;钻石矿石
- 57;钻石块;钻石块
- 58;工作台;工作台
- 59;小麦;小麦
- 60;耕地;耕地
- 61;熔炉;熔炉
- 62;燃烧的熔炉;燃烧的熔炉
- 63;站立的告示牌 ;站立的告示牌 
- 64;木门;木门
- 65;梯子;梯子
- 66;铁轨;铁轨
- 67;圆石楼梯;圆石楼梯
- 68;墙上的告示牌;墙上的告示牌
- 69;拉杆;拉杆
- 70;石质压力板;石质压力板
- 71;铁门;铁门
- 72;木质压力板;木质压力板
- 73;红石矿石;红石矿石
- 74;发光的红石矿石;发光的红石矿石
- 75;红石火把;红石火把
- 76;红石火把;红石火把
- 77;石质按钮;石质按钮
- 78;雪;雪
- 79;冰;冰 
- 80;雪块;雪块
- 81;仙人掌;仙人掌
- 82;粘土;粘土
- 83;甘蔗;甘蔗
- 84;唱片机;唱片机
- 85;栅栏;栅栏
- 86;南瓜;南瓜
- 87;地狱岩;地狱岩
- 88;灵魂沙;灵魂沙
- 89;萤石;萤石
- 90;下界传送门;下界传送门
- 91;南瓜灯;南瓜灯
- 92;蛋糕;蛋糕
- 93;红石中继器;红石中继器
- 94;红石中继器;红石中继器
- 95;染色玻璃 ;染色玻璃 
- 96;活板门;活板门
- 97;怪物蛋;怪物蛋
- 98;石砖;石砖
- 99;棕色巨型蘑菇;棕色巨型蘑菇
- 100;红色巨型蘑菇;红色巨型蘑菇
- 101;铁栏杆;铁栏杆
- 102;玻璃板;玻璃板
- 103;西瓜片;西瓜片
- 104;南瓜梗;南瓜梗
- 105;西瓜梗;西瓜梗
- 106;藤蔓;藤蔓
- 107;栅栏门;栅栏门
- 108;砖块楼梯;砖块楼梯
- 109;石砖楼梯;石砖楼梯
- 110;菌丝;菌丝
- 111;睡莲;睡莲 
- 112;地狱砖块;地狱砖块
- 113;地狱砖栅栏;地狱砖栅栏
- 114;地狱砖楼梯;地狱砖楼梯
- 115;地狱疣;地狱疣
- 116;附魔台;附魔台
- 117;酿造台;酿造台
- 118;炼药锅;炼药锅
- 119;末地传送门;末地传送门
- 120;末地传送门框架;末地传送门框架
- 121;末地石;末地石
- 122;龙蛋;龙蛋
- 123;红石灯;红石灯
- 124;红石灯;红石灯
- 125;双木台阶;双木台阶
- 126;木台阶;木台阶
- 127;可可果 ;可可果 
- 128;沙石楼梯;沙石楼梯
- 129;绿宝石矿石;绿宝石矿石
- 130;末影箱;末影箱
- 131;绊线钩;绊线钩
- 132;绊线;绊线
- 133;绿宝石块;绿宝石块
- 134;云杉楼梯;云杉楼梯
- 135;桦木楼梯;桦木楼梯
- 136;丛林楼梯;丛林楼梯
- 137;命令方块;命令方块
- 138;信标;信标
- 139;圆石墙;圆石墙
- 140;花盆;花盆
- 141;胡萝卜;胡萝卜
- 142;马铃薯;马铃薯
- 143;木质按钮 ;木质按钮 
- 144;生物头颅;生物头颅
- 145;铁砧;铁砧
- 146;陷阱箱;陷阱箱
- 147;轻质测重压力板;轻质测重压力板
- 148;重质测重压力板;重质测重压力板
- 149;红石比较器;红石比较器
- 150;红石比较器;红石比较器
- 151;阳光传感器;阳光传感器
- 152;红石块;红石块
- 153;下界石英矿石;下界石英矿石
- 154;漏斗;漏斗
- 155;石英块;石英块
- 156;石英楼梯;石英楼梯
- 157;激活铁轨;激活铁轨
- 158;投掷器;投掷器
- 159;染色粘土 ;染色粘土 
- 160;染色玻璃板;染色玻璃板
- 161;树叶(金合欢/深色橡木);树叶(金合欢/深色橡木)
- 162;木头(金合欢/深色橡木);木头(金合欢/深色橡木)
- 163;金合欢楼梯;金合欢楼梯
- 164;深色橡木楼梯;深色橡木楼梯
- 165;粘液块;粘液块
- 166;屏障;屏障
- 167;铁活板门;铁活板门
- 168;海晶石;海晶石
- 169;海晶灯;海晶灯
- 170;干草块;干草块
- 171;地毯;地毯
- 172;硬化粘土;硬化粘土
- 173;煤炭块;煤炭块
- 174;浮冰;浮冰
- 175;大型花 ;大型花 
- 176;站立的旗帜;站立的旗帜
- 177;墙上的旗帜;墙上的旗帜
- 178;反向阳光传感器;反向阳光传感器
- 179;红沙石;红沙石
- 180;红沙石楼梯;红沙石楼梯
- 181;双红沙石台阶;双红沙石台阶
- 182;红沙石台阶;红沙石台阶
- 183;云杉木栅栏门;云杉木栅栏门
- 184;白桦木栅栏门;白桦木栅栏门
- 185;丛林木栅栏门;丛林木栅栏门
- 186;深色橡木栅栏门;深色橡木栅栏门
- 187;金合欢栅栏门;金合欢栅栏门
- 188;云杉木栅栏;云杉木栅栏
- 189;白桦木栅栏;白桦木栅栏
- 190;丛林木栅栏;丛林木栅栏
- 191;深色橡木栅栏 ;深色橡木栅栏 
- 192;金合欢栅栏;金合欢栅栏
- 193;云杉木门;云杉木门
- 194;白桦木门;白桦木门
- 195;丛林木门;丛林木门
- 196;金合欢木门;金合欢木门
- 197;深色橡木门;深色橡木门
- 198;末地烛;末地烛
- 199;紫颂植物;紫颂植物
- 200;紫颂花;紫颂花
- 201;紫珀块;紫珀块
- 202;竖纹紫珀块;竖纹紫珀块
- 203;紫珀块楼梯;紫珀块楼梯
- 204;双紫珀台阶;双紫珀台阶
- 205;紫珀块台阶;紫珀块台阶
- 206;末地石砖;末地石砖
- 207;甜菜种子 ;甜菜种子 
- 208;草径;草径
- 209;末地折跃门方块;末地折跃门方块
- 210;循环型命令方块;循环型命令方块
- 211;连锁型命令方块;连锁型命令方块
- 212;霜冰;霜冰
- 213;岩浆块;岩浆块
- 214;地狱疣块;地狱疣块
- 215;红色地狱砖;红色地狱砖
- 216;骨块;骨块
- 217;结构空位;结构空位
- 255;结构方块;结构方块
#以上方块，以下物品
- 256;铁锹;铁锹
- 257;铁镐;铁镐
- 258;铁斧;铁斧
- 259;打火石;打火石
- 260;苹果;苹果
- 261;弓;弓
- 262;箭;箭
- 263;煤炭;煤炭
- 264;钻石;钻石
- 265;铁锭;铁锭
- 266;金锭;金锭
- 267;铁剑;铁剑
- 268;木剑;木剑
- 269;木锹;木锹
- 270;木镐;木镐
- 271;木斧 ;木斧 
- 272;石剑;石剑
- 273;石锹;石锹
- 274;石镐;石镐
- 275;石斧;石斧
- 276;钻石剑;钻石剑
- 277;钻石锹;钻石锹
- 278;钻石镐;钻石镐
- 279;钻石斧;钻石斧
- 280;木棍;木棍
- 281;碗;碗
- 282;蘑菇煲;蘑菇煲
- 283;金剑;金剑
- 284;金锹;金锹
- 285;金镐;金镐
- 286;金斧;金斧
- 287;线 ;线 
- 288;羽毛;羽毛
- 289;火药;火药
- 290;木锄;木锄
- 291;石锄;石锄
- 292;铁锄;铁锄
- 293;钻石锄;钻石锄
- 294;金锄;金锄
- 295;小麦种子;小麦种子
- 296;小麦;小麦
- 297;面包;面包
- 298;皮革帽子;皮革帽子
- 299;皮革外套;皮革外套
- 300;皮革裤子;皮革裤子
- 301;皮革靴子;皮革靴子
- 302;锁链头盔;锁链头盔
- 303;锁链胸甲 ;锁链胸甲 
- 304;锁链护腿;锁链护腿
- 305;锁链靴子;锁链靴子
- 306;铁头盔;铁头盔
- 307;铁胸甲;铁胸甲
- 308;铁护腿;铁护腿
- 309;铁靴子;铁靴子
- 310;钻石头盔;钻石头盔
- 311;钻石胸甲;钻石胸甲
- 312;钻石护腿;钻石护腿
- 313;钻石靴子;钻石靴子
- 314;金头盔;金头盔
- 315;金胸甲;金胸甲
- 316;金护腿;金护腿
- 317;金靴子;金靴子
- 318;燧石;燧石
- 319;生猪排 ;生猪排 
- 320;熟猪排;熟猪排
- 321;画;画
- 322;金苹果;金苹果
- 323;告示牌;告示牌
- 324;木门;木门
- 325;桶;桶
- 326;水桶;水桶
- 327;熔岩桶;熔岩桶
- 328;矿车;矿车
- 329;鞍;鞍
- 330;铁门;铁门
- 331;红石粉;红石粉
- 332;雪球;雪球
- 333;船;船
- 334;皮革;皮革
- 335;牛奶 ;牛奶 
- 336;红砖;红砖
- 337;粘土;粘土
- 338;甘蔗;甘蔗
- 339;纸;纸
- 340;书;书
- 341;粘液球;粘液球
- 342;运输矿车;运输矿车
- 343;动力矿车;动力矿车
- 344;鸡蛋;鸡蛋
- 345;指南针;指南针
- 346;钓鱼竿;钓鱼竿
- 347;钟;钟
- 348;萤石粉;萤石粉
- 349;生鱼;生鱼
- 350;熟鱼;熟鱼
- 351;染料 ;染料 
- 352;骨头;骨头
- 353;糖;糖
- 354;蛋糕;蛋糕
- 355;床;床
- 356;红石中继器;红石中继器
- 357;曲奇;曲奇
- 358;地图;地图
- 359;剪刀;剪刀
- 360;西瓜片;西瓜片
- 361;南瓜种子;南瓜种子
- 362;西瓜种子;西瓜种子
- 363;生牛肉;生牛肉
- 364;牛排;牛排
- 365;生鸡肉;生鸡肉
- 366;熟鸡肉;熟鸡肉
- 367;腐肉 ;腐肉 
- 368;末影珍珠;末影珍珠
- 369;烈焰棒;烈焰棒
- 370;恶魂之泪;恶魂之泪
- 371;金粒;金粒
- 372;地狱疣;地狱疣
- 373;药水;药水
- 374;玻璃瓶;玻璃瓶
- 375;蜘蛛眼;蜘蛛眼
- 376;发酵蛛眼;发酵蛛眼
- 377;烈焰粉;烈焰粉
- 378;岩浆膏;岩浆膏
- 379;酿造台;酿造台
- 380;炼药锅;炼药锅
- 381;末影之眼;末影之眼
- 382;闪烁的西瓜;闪烁的西瓜
- 383;刷怪蛋 ;刷怪蛋 
- 384;附魔之瓶;附魔之瓶
- 385;火焰弹;火焰弹
- 386;书与笔;书与笔
- 387;成书;成书
- 388;绿宝石;绿宝石
- 389;物品展示框;物品展示框
- 390;花盆;花盆
- 391;胡萝卜;胡萝卜
- 392;马铃薯;马铃薯
- 393;烤马铃薯;烤马铃薯
- 394;毒马铃薯;毒马铃薯
- 395;空地图;空地图
- 396;金胡萝卜;金胡萝卜
- 397;生物头颅;生物头颅
- 398;胡萝卜钓竿;胡萝卜钓竿
- 399;下界之星 ;下界之星 
- 400;南瓜派;南瓜派
- 401;烟花火箭;烟花火箭
- 402;烟火之星;烟火之星
- 403;附魔书;附魔书
- 404;红石比较器;红石比较器
- 405;地狱砖;地狱砖
- 406;下界石英;下界石英
- 407;TNT矿车;TNT矿车
- 408;漏斗矿车;漏斗矿车
- 409;海晶碎片;海晶碎片
- 410;海晶砂粒;海晶砂粒
- 411;生兔肉;生兔肉
- 412;熟兔肉;熟兔肉
- 413;兔肉煲;兔肉煲
- 414;兔子脚;兔子脚
- 415;兔子皮 ;兔子皮 
- 416;盔甲架;盔甲架
- 417;铁马铠;铁马铠
- 418;金马铠;金马铠
- 419;钻石马铠;钻石马铠
- 420;拴绳;拴绳
- 421;命名牌;命名牌
- 422;命令方块矿车;命令方块矿车
- 423;生羊肉;生羊肉
- 424;熟羊肉;熟羊肉
- 425;旗帜;旗帜
- 426;末影水晶;末影水晶
- 427;云杉木门;云杉木门
- 428;白桦木门;白桦木门
- 429;丛林木门;丛林木门
- 430;金合欢木门;金合欢木门
- 431;深色橡木门 ;深色橡木门 
- 432;紫颂果;紫颂果
- 433;爆裂紫颂果;爆裂紫颂果
- 434;甜菜根;甜菜根
- 435;甜菜种子;甜菜种子
- 436;甜菜汤;甜菜汤
- 437;龙息;龙息
- 438;喷溅药水;喷溅药水
- 439;光灵箭;光灵箭
- 440;药箭;药箭
- 441;滞留药水;滞留药水
- 442;盾牌;盾牌
- 443;鞘翅;鞘翅
- 444;云杉船;云杉船
- 445;白桦船;白桦船
- 446;丛林船;丛林船
- 447;金合欢船 ;金合欢船 
- 448;深色橡木船;深色橡木船
- 2256;13唱片;13唱片
- 2257;cat唱片;cat唱片
- 2258;blocks唱片;blocks唱片
- 2259;chirp唱片;chirp唱片
- 2260;far唱片;far唱片
- 2261;mall唱片;mall唱片
- 2262;mellohi唱片;mellohi唱片
- 2263;stal唱片;stal唱片
- 2264;strad唱片;strad唱片
- 2265;ward唱片;ward唱片
- 2266;11唱片;11唱片
- 2267;wait唱片;wait唱片
#以上翻译均来自wiki

custom-potions-name:
  format-full: "%splash %type %tier"
  format-sign: "%splash%type%tier"
  splash-sign: "喷溅型"
  splash-full: "喷溅型"
  
  #Custom names for potions types. Format: <PotionType>;<CustomSignName>;<CustomFullName>
  #自定义药水类型
  # PotionType: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionType.html
  types:
  #- INVISIBILITY;Invis.Potion;Potion of Invisibility
  - AWKWARD;粗制的药水;粗制的药水
  - FIRE_RESISTANCE;抗火药水;抗火药水
  - INSTANT_DAMAGE;伤害药水;伤害药水
  - INSTANT_HEAL;恢复药水;恢复药水
  - INVISIBILITY;隐身药水;隐身药水
  - JUMP;跳跃药水;跳跃药水
  - LUCK;幸运药水;幸运药水
  - MUNDANE;平凡的药水;平凡的药水
  - NIGHT_VISION;夜视药水;夜视药水
  - POISON;剧毒药水;剧毒药水
  - REGEN;再生药水;再生药水
  - SLOWNESS;迟缓药水;迟缓药水
  - SPEED;迅捷药水;迅捷药水
  - STRENGTH;力量药水;力量药水
  - THICK;浑浊的药水;浑浊的药水
  - WATER;水瓶;水瓶
  - WATER_BREATHING;水肺药水;水肺药水
  - WEAKNESS;虚弱药水;虚弱药水
  #以上翻译均来自wiki

  #Custom names for potion effect type. Format: <PotionEffectType>;<CustomName>
  #自定义药水效果类型
  # PotionEffect: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
  effects:
  #- FIRE_RESISTANCE;Fire resistance
  #- INVISIBILITY;Invisibility
  - SPEED;速度
  - SLOW;缓慢
  - FAST_DIGGING;急迫
  - SLOW_DIGGING;挖掘疲劳
  - INCREASE_DAMAGE;力量
  - HEAL;瞬间治疗
  - HARM;瞬间伤害
  - JUMP;跳跃提升
  - CONFUSION;反胃
  - REGENERATION;生命恢复
  - DAMAGE_RESISTANCE;抗性提升
  - FIRE_RESISTANCE;防火
  - WATER_BREATHING;水下呼吸
  - INVISIBILITY;隐身
  - BLINDNESS;失明
  - NIGHT_VISION;夜视
  - HUNGER;饥饿
  - WEAKNESS;虚弱
  - POISON;中毒
  - WITHER;凋零
  - HEALTH_BOOST;生命提升
  - ABSORPTION;伤害吸收
  - SATURATION;饱和
  - GLOWING;发光
  - LEVITATION;飘浮
  - LUCK;幸运
  - UNLUCK;霉运
  #以上翻译均来自wiki
  